version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - copyloopvar # https://github.com/karamaru-alpha/copyloopvar?tab=readme-ov-file
    - errchkjson # https://github.com/breml/errchkjson
    - errname # https://github.com/Antonboom/errname
    - errorlint # https://github.com/polyfloyd/go-errorlint
    - exhaustive # https://github.com/nishanths/exhaustive
    - exptostd # https://github.com/ldez/exptostd
    - gocritic # https://github.com/go-critic/go-critic?tab=readme-ov-file
    - loggercheck # https://github.com/timonwong/loggercheck
    - perfsprint # https://github.com/catenacyber/perfsprint
    - prealloc # https://github.com/alexkohler/prealloc
    - revive # https://github.com/mgechev/revive?tab=readme-ov-file#available-rules
    - unconvert # https://github.com/mdempsky/unconvert
    - unparam # https://github.com/mvdan/unparam

  settings:
    copyloopvar:
      check-alias: true
    errchkjson:
      report-no-exported: true
    exhaustive:
      default-signifies-exhaustive: true
    loggercheck:
      kitlog: false
      klog: false
      logr: false
      slog: false
