services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - events_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio miniominio;
      /usr/bin/mc mb -p myminio/events;
      exit 0;
      "

  backend:
    build:
      dockerfile: Dockerfile.dev
    command: sh -c "go mod tidy && air -c .air.toml"
    ports:
      - 4000:4000
    volumes:
      - .:/backend
      - /backend/ui
      - backend_packages:/go/pkg/mod
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started
      createbuckets:
        condition: service_completed_successfully

  frontend:
    build:
      context: ui
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./ui:/frontend
      - frontend_packages:/frontend/node_modules
    depends_on:
      - backend

volumes:
  events_data:
  minio_data:
  backend_packages:
  frontend_packages:
