services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - events_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/backend
      - /backend/ui
      - backend_packages:/go/pkg/mod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  frontend:
    build:
      context: ui
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./ui:/frontend
      - frontend_packages:/frontend/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  events_data:
  backend_packages:
  frontend_packages:
