// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: announcement_event.sql

package sqlc

import (
	"context"
)

const announcementEventCreateBatch = `-- name: AnnouncementEventCreateBatch :exec
INSERT INTO announcement_event (announcement_id, event_id)
VALUES (
  UNNEST($1::int[]),
  UNNEST($2::int[])
)
`

type AnnouncementEventCreateBatchParams struct {
	Column1 []int32
	Column2 []int32
}

func (q *Queries) AnnouncementEventCreateBatch(ctx context.Context, arg AnnouncementEventCreateBatchParams) error {
	_, err := q.db.Exec(ctx, announcementEventCreateBatch, arg.Column1, arg.Column2)
	return err
}
