// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: check_status.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkStatusCreate = `-- name: CheckStatusCreate :one
INSERT INTO check_status (event_id, check_id, status, message)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CheckStatusCreateParams struct {
	EventID int32
	CheckID int32
	Status  CheckStatusEnum
	Message pgtype.Text
}

func (q *Queries) CheckStatusCreate(ctx context.Context, arg CheckStatusCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, checkStatusCreate,
		arg.EventID,
		arg.CheckID,
		arg.Status,
		arg.Message,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const checkStatusGetByEvent = `-- name: CheckStatusGetByEvent :many
SELECT id, event_id, check_id, status, message
FROM check_status
WHERE event_id = $1
`

func (q *Queries) CheckStatusGetByEvent(ctx context.Context, eventID int32) ([]CheckStatus, error) {
	rows, err := q.db.Query(ctx, checkStatusGetByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckStatus
	for rows.Next() {
		var i CheckStatus
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.CheckID,
			&i.Status,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkStatusUpdate = `-- name: CheckStatusUpdate :exec
UPDATE check_status
SET status = $2, message = $3
WHERE id = $1
`

type CheckStatusUpdateParams struct {
	ID      int32
	Status  CheckStatusEnum
	Message pgtype.Text
}

func (q *Queries) CheckStatusUpdate(ctx context.Context, arg CheckStatusUpdateParams) error {
	_, err := q.db.Exec(ctx, checkStatusUpdate, arg.ID, arg.Status, arg.Message)
	return err
}
