// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: check_custom.sql

package sqlc

import (
	"context"
)

const checkCustomCreate = `-- name: CheckCustomCreate :one
INSERT INTO check_custom (event_id, description, status, creator_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CheckCustomCreateParams struct {
	EventID     int32
	Description string
	Status      CheckStatusEnum
	CreatorID   int32
}

func (q *Queries) CheckCustomCreate(ctx context.Context, arg CheckCustomCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, checkCustomCreate,
		arg.EventID,
		arg.Description,
		arg.Status,
		arg.CreatorID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const checkCustomGet = `-- name: CheckCustomGet :one
SELECT id, event_id, description, status, creator_id
FROM check_custom
WHERE id = $1
`

func (q *Queries) CheckCustomGet(ctx context.Context, id int32) (CheckCustom, error) {
	row := q.db.QueryRow(ctx, checkCustomGet, id)
	var i CheckCustom
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Description,
		&i.Status,
		&i.CreatorID,
	)
	return i, err
}

const checkCustomGetByEvent = `-- name: CheckCustomGetByEvent :many
SELECT id, event_id, description, status, creator_id
FROM check_custom
WHERE event_id = $1
`

func (q *Queries) CheckCustomGetByEvent(ctx context.Context, eventID int32) ([]CheckCustom, error) {
	rows, err := q.db.Query(ctx, checkCustomGetByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckCustom
	for rows.Next() {
		var i CheckCustom
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Description,
			&i.Status,
			&i.CreatorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkCustomUpdate = `-- name: CheckCustomUpdate :exec
UPDATE check_custom
SET description = $2, status = $3
WHERE id = $1
`

type CheckCustomUpdateParams struct {
	ID          int32
	Description string
	Status      CheckStatusEnum
}

func (q *Queries) CheckCustomUpdate(ctx context.Context, arg CheckCustomUpdateParams) error {
	_, err := q.db.Exec(ctx, checkCustomUpdate, arg.ID, arg.Description, arg.Status)
	return err
}
