// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: check.sql

package sqlc

import (
	"context"
)

const checkCreate = `-- name: CheckCreate :one
INSERT INTO "check" (description, deadline)
VALUES ($1, $2)
RETURNING id
`

type CheckCreateParams struct {
	Description string
	Deadline    int64
}

func (q *Queries) CheckCreate(ctx context.Context, arg CheckCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, checkCreate, arg.Description, arg.Deadline)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const checkGetAll = `-- name: CheckGetAll :many
SELECT id, description, deadline
FROM "check"
`

func (q *Queries) CheckGetAll(ctx context.Context) ([]Check, error) {
	rows, err := q.db.Query(ctx, checkGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Check
	for rows.Next() {
		var i Check
		if err := rows.Scan(&i.ID, &i.Description, &i.Deadline); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
