// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: image.sql

package sqlc

import (
	"context"
)

const imageCreate = `-- name: ImageCreate :one
INSERT INTO image (name, file_id)
VALUES ($1, $2)
RETURNING id
`

type ImageCreateParams struct {
	Name   string
	FileID string
}

func (q *Queries) ImageCreate(ctx context.Context, arg ImageCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, imageCreate, arg.Name, arg.FileID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const imageGet = `-- name: ImageGet :one
SELECT id, name, file_id
FROM image
WHERE id = $1
`

func (q *Queries) ImageGet(ctx context.Context, id int32) (Image, error) {
	row := q.db.QueryRow(ctx, imageGet, id)
	var i Image
	err := row.Scan(&i.ID, &i.Name, &i.FileID)
	return i, err
}
