// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mail.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const mailCreate = `-- name: MailCreate :one
INSERT INTO mail (year_id, author_id, title, content, send_time, send, error)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type MailCreateParams struct {
	YearID   int32
	AuthorID int32
	Title    string
	Content  string
	SendTime pgtype.Timestamptz
	Send     bool
	Error    pgtype.Text
}

func (q *Queries) MailCreate(ctx context.Context, arg MailCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, mailCreate,
		arg.YearID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.SendTime,
		arg.Send,
		arg.Error,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const mailDelete = `-- name: MailDelete :exec
DELETE FROM mail
WHERE id = $1
AND NOT send AND error IS NULL
`

func (q *Queries) MailDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, mailDelete, id)
	return err
}

const mailError = `-- name: MailError :exec
UPDATE mail
SET error = $1
WHERE id = $2
`

type MailErrorParams struct {
	Error pgtype.Text
	ID    int32
}

func (q *Queries) MailError(ctx context.Context, arg MailErrorParams) error {
	_, err := q.db.Exec(ctx, mailError, arg.Error, arg.ID)
	return err
}

const mailGetByEvents = `-- name: MailGetByEvents :many
SELECT m.id, content, send_time, send, error, title, year_id, author_id, m_e.id, mail_id, event_id
FROM mail m
LEFT JOIN mail_event m_e ON m_e.mail_id = m.id
WHERE m_e.event_id = ANY($1::int[])
ORDER BY send_time
`

type MailGetByEventsRow struct {
	ID       int32
	Content  string
	SendTime pgtype.Timestamptz
	Send     bool
	Error    pgtype.Text
	Title    string
	YearID   int32
	AuthorID int32
	ID_2     pgtype.Int4
	MailID   pgtype.Int4
	EventID  pgtype.Int4
}

func (q *Queries) MailGetByEvents(ctx context.Context, dollar_1 []int32) ([]MailGetByEventsRow, error) {
	rows, err := q.db.Query(ctx, mailGetByEvents, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailGetByEventsRow
	for rows.Next() {
		var i MailGetByEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SendTime,
			&i.Send,
			&i.Error,
			&i.Title,
			&i.YearID,
			&i.AuthorID,
			&i.ID_2,
			&i.MailID,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailGetByID = `-- name: MailGetByID :many
SELECT m.id, content, send_time, send, error, title, year_id, author_id, m_e.id, mail_id, event_id
FROM mail m
LEFT JOIN mail_event m_e ON m_e.mail_id = m.id
WHERE m.id = $1
`

type MailGetByIDRow struct {
	ID       int32
	Content  string
	SendTime pgtype.Timestamptz
	Send     bool
	Error    pgtype.Text
	Title    string
	YearID   int32
	AuthorID int32
	ID_2     pgtype.Int4
	MailID   pgtype.Int4
	EventID  pgtype.Int4
}

func (q *Queries) MailGetByID(ctx context.Context, id int32) ([]MailGetByIDRow, error) {
	rows, err := q.db.Query(ctx, mailGetByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailGetByIDRow
	for rows.Next() {
		var i MailGetByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SendTime,
			&i.Send,
			&i.Error,
			&i.Title,
			&i.YearID,
			&i.AuthorID,
			&i.ID_2,
			&i.MailID,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailGetByYear = `-- name: MailGetByYear :many
SELECT m.id, content, send_time, send, error, title, year_id, author_id, m_e.id, mail_id, event_id
FROM mail m
LEFT JOIN mail_event m_e ON m_e.mail_id = m.id
WHERE m.year_id = $1
ORDER BY m.send_time
`

type MailGetByYearRow struct {
	ID       int32
	Content  string
	SendTime pgtype.Timestamptz
	Send     bool
	Error    pgtype.Text
	Title    string
	YearID   int32
	AuthorID int32
	ID_2     pgtype.Int4
	MailID   pgtype.Int4
	EventID  pgtype.Int4
}

func (q *Queries) MailGetByYear(ctx context.Context, yearID int32) ([]MailGetByYearRow, error) {
	rows, err := q.db.Query(ctx, mailGetByYear, yearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailGetByYearRow
	for rows.Next() {
		var i MailGetByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SendTime,
			&i.Send,
			&i.Error,
			&i.Title,
			&i.YearID,
			&i.AuthorID,
			&i.ID_2,
			&i.MailID,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailGetUnsend = `-- name: MailGetUnsend :many
SELECT m.id, content, send_time, send, error, title, year_id, author_id, m_e.id, mail_id, event_id
FROM mail m
LEFT JOIN mail_event m_e ON m_e.mail_id = m.id
WHERE NOT send AND error IS NULL
`

type MailGetUnsendRow struct {
	ID       int32
	Content  string
	SendTime pgtype.Timestamptz
	Send     bool
	Error    pgtype.Text
	Title    string
	YearID   int32
	AuthorID int32
	ID_2     pgtype.Int4
	MailID   pgtype.Int4
	EventID  pgtype.Int4
}

func (q *Queries) MailGetUnsend(ctx context.Context) ([]MailGetUnsendRow, error) {
	rows, err := q.db.Query(ctx, mailGetUnsend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailGetUnsendRow
	for rows.Next() {
		var i MailGetUnsendRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SendTime,
			&i.Send,
			&i.Error,
			&i.Title,
			&i.YearID,
			&i.AuthorID,
			&i.ID_2,
			&i.MailID,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailSend = `-- name: MailSend :exec
UPDATE mail
SET send = true
WHERE id = $1
`

func (q *Queries) MailSend(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, mailSend, id)
	return err
}

const mailUpdate = `-- name: MailUpdate :exec
UPDATE mail
SET title = $1, content = $2, send_time = $3
WHERE id = $4 AND NOT send AND error IS NULL
`

type MailUpdateParams struct {
	Title    string
	Content  string
	SendTime pgtype.Timestamptz
	ID       int32
}

func (q *Queries) MailUpdate(ctx context.Context, arg MailUpdateParams) error {
	_, err := q.db.Exec(ctx, mailUpdate,
		arg.Title,
		arg.Content,
		arg.SendTime,
		arg.ID,
	)
	return err
}
