// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mail.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const mailCreate = `-- name: MailCreate :one
INSERT INTO mail (content, send_time, send, error)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type MailCreateParams struct {
	Content  string
	SendTime pgtype.Timestamptz
	Send     bool
	Error    pgtype.Text
}

func (q *Queries) MailCreate(ctx context.Context, arg MailCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, mailCreate,
		arg.Content,
		arg.SendTime,
		arg.Send,
		arg.Error,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const mailError = `-- name: MailError :exec
UPDATE mail
SET error = $1
WHERE id = $2
`

type MailErrorParams struct {
	Error pgtype.Text
	ID    int32
}

func (q *Queries) MailError(ctx context.Context, arg MailErrorParams) error {
	_, err := q.db.Exec(ctx, mailError, arg.Error, arg.ID)
	return err
}

const mailGetAll = `-- name: MailGetAll :many
SELECT id, content, send_time, send, error
FROM mail
ORDER BY send_time
`

func (q *Queries) MailGetAll(ctx context.Context) ([]Mail, error) {
	rows, err := q.db.Query(ctx, mailGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mail
	for rows.Next() {
		var i Mail
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SendTime,
			&i.Send,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailGetUnsend = `-- name: MailGetUnsend :many
SELECT id, content, send_time, send, error
FROM mail
WHERE NOT send AND error IS NULL
`

func (q *Queries) MailGetUnsend(ctx context.Context) ([]Mail, error) {
	rows, err := q.db.Query(ctx, mailGetUnsend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mail
	for rows.Next() {
		var i Mail
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SendTime,
			&i.Send,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailSend = `-- name: MailSend :exec
UPDATE mail
SET send = true
WHERE id = $1
`

func (q *Queries) MailSend(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, mailSend, id)
	return err
}

const mailUpdate = `-- name: MailUpdate :exec
UPDATE mail
SET content = $1, send_time = $2
WHERE id = $3 AND NOT send
`

type MailUpdateParams struct {
	Content  string
	SendTime pgtype.Timestamptz
	ID       int32
}

func (q *Queries) MailUpdate(ctx context.Context, arg MailUpdateParams) error {
	_, err := q.db.Exec(ctx, mailUpdate, arg.Content, arg.SendTime, arg.ID)
	return err
}
