// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicYear struct {
	ID        int32
	StartYear int32
	EndYear   int32
}

type Board struct {
	ID           int32
	Member       int32
	AcademicYear int32
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Event struct {
	ID           int32
	Url          string
	Name         string
	Description  pgtype.Text
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Location     pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	AcademicYear int32
}

type Member struct {
	ID       int32
	Name     string
	Username pgtype.Text
}

type Organizer struct {
	ID    int32
	Event int32
	Board int32
}
