// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: poster.sql

package sqlc

import (
	"context"
)

const posterCreate = `-- name: PosterCreate :one
INSERT INTO poster (event_id, file_id, scc)
VALUES ($1, $2, $3)
RETURNING id
`

type PosterCreateParams struct {
	EventID int32
	FileID  string
	Scc     bool
}

func (q *Queries) PosterCreate(ctx context.Context, arg PosterCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, posterCreate, arg.EventID, arg.FileID, arg.Scc)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const posterDelete = `-- name: PosterDelete :exec
DELETE FROM poster
WHERE id = $1
`

func (q *Queries) PosterDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, posterDelete, id)
	return err
}

const posterGet = `-- name: PosterGet :one
SELECT id, event_id, file_id, scc
FROM poster
WHERE id = $1
`

func (q *Queries) PosterGet(ctx context.Context, id int32) (Poster, error) {
	row := q.db.QueryRow(ctx, posterGet, id)
	var i Poster
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.FileID,
		&i.Scc,
	)
	return i, err
}

const posterUpdate = `-- name: PosterUpdate :exec
UPDATE poster
SET event_id = $1, file_id = $2, scc = $3
WHERE id = $4
`

type PosterUpdateParams struct {
	EventID int32
	FileID  string
	Scc     bool
	ID      int32
}

func (q *Queries) PosterUpdate(ctx context.Context, arg PosterUpdateParams) error {
	_, err := q.db.Exec(ctx, posterUpdate,
		arg.EventID,
		arg.FileID,
		arg.Scc,
		arg.ID,
	)
	return err
}
