app:
  name: events
  host: 0.0.0.0

db:
  host: db
  port: 5432
  database: events
  user: postgres
  password: postgres

minio:
  endpoint: minio:9000
  username: minio
  password: miniominio
  bucket: events
  secure: false

storage:
  provider: minio

auth:
  client: tomtest
  secret: blargh
  callback_url: http://localhost:4000/api/auth/callback/zauth
  redirect_url: http://localhost:3000

mail:
  deadline_s: 0

website:
  events_s: 86400 # 1 day
  boards_s: 86400 # 1 day

dsa:
  deadline_s: 259200 # 3 days
  syncronize_s: 86400 # 1 day

announcement:
  channel: c48qqzyfp7dhjciniwbk7k8fgy # Test kanaal
  deadline_s: 172800 # 2 days

check:
  sync_s: 3600 # 1 hour

poster:
  sync_s: 86400 # 1 day
  big_deadline_s: 0
  scc_deadline_s: 0
