app:
  name: events

db:
  host: db
  port: 5432
  database: events
  user: postgres
  password: postgres

auth:
  client: tomtest
  secret: blargh
  callback_url: http://localhost:4000/api/auth/callback/zauth
  redirect_url: http://localhost:5173

mail:
  from: Events
  from_address: events@zeus.ugent.be
  host: smtp.ugent.be
  port: 25

website:
  years_s: 86400
  events_s: 3600
  boards_s: 86400
