app:
  name: events

db:
  host: db
  port: 5432
  database: events
  user: postgres
  password: postgres

storage:
  provider: minio

minio:
  endpoint: minio:9000
  username: minio
  password: miniominio

auth:
  client: tomtest
  secret: blargh
  callback_url: http://localhost:4000/api/auth/callback/zauth
  redirect_url: http://localhost:5173

mail:
  from: Events
  from_address: events@zeus.ugent.be
  host: smtp.ugent.be
  port: 25

website:
  events_s: 86400
  boards_s: 86400

dsa:
  url: "https://dsa.ugent.be/api/activiteiten?page_size=100&association=zeus"
  activities_s: 3600

mattermost:
  url: https://mattermost.zeus.gent
  announcement_channel: c48qqzyfp7dhjciniwbk7k8fgy # Test kanaal

gitmate:
  url: "https://git.zeus.gent/api/v1/repos/ZeusWPI/visueel"

poster:
  sync_s: 86400
