// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: event.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const eventCreate = `-- name: EventCreate :one
INSERT INTO event (url, name, description, start_time, end_time, academic_year, location)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type EventCreateParams struct {
	Url          string
	Name         string
	Description  pgtype.Text
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	AcademicYear int32
	Location     pgtype.Text
}

func (q *Queries) EventCreate(ctx context.Context, arg EventCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, eventCreate,
		arg.Url,
		arg.Name,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.AcademicYear,
		arg.Location,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const eventDelete = `-- name: EventDelete :exec
UPDATE event 
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) EventDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, eventDelete, id)
	return err
}

const eventGetAll = `-- name: EventGetAll :many
SELECT id, url, name, description, start_time, end_time, location, created_at, updated_at, deleted_at, academic_year FROM event
`

func (q *Queries) EventGetAll(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, eventGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Name,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AcademicYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventUpdate = `-- name: EventUpdate :exec
UPDATE event 
SET url = $1, name = $2, description = $3, start_time = $4, end_time = $5, academic_year = $6, location = $7, updated_at = CURRENT_TIMESTAMP, deleted_at = NULL
WHERE id = $8
`

type EventUpdateParams struct {
	Url          string
	Name         string
	Description  pgtype.Text
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	AcademicYear int32
	Location     pgtype.Text
	ID           int32
}

func (q *Queries) EventUpdate(ctx context.Context, arg EventUpdateParams) error {
	_, err := q.db.Exec(ctx, eventUpdate,
		arg.Url,
		arg.Name,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.AcademicYear,
		arg.Location,
		arg.ID,
	)
	return err
}
